[package]
name = "lu"
version = "0.1.0"
edition = "2021"
[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
oneparse = "0.1.0"
[profile.release]
opt-level = 's'
codegen-units = 1
lto = true
panic = "abort"